### ISSUE TITLE
Inference in mlp model crashes 

### ISSUE THREAD

**Issue by rruizdeaustri** [Yura52/tabular-dl-revisiting-models#21]
Hi Yuri,

I have converted the data for a suitable format for the models in the repo. but I'm having 
some issues in the inference step.

Running the mlp model I get:

File "bin/mlp.py", line 251, in <module>
   metrics, predictions = evaluate([lib.VAL, lib.TEST])
 File "/r5/home/rruiz/software/anaconda3/envs/revisiting-models/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
   return func(*args, **kwargs)
 File "bin/mlp.py", line 167, in evaluate
   [
 File "bin/mlp.py", line 168, in <listcomp>
   model(
 File "/r5/home/rruiz/software/anaconda3/envs/revisiting-models/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
   result = self.forward(*input, **kwargs)
 File "bin/mlp.py", line 52, in forward
   print(self.category_embeddings(x_cat + self.category_offsets[None]))
 File "/r5/home/rruiz/software/anaconda3/envs/revisiting-models/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
   result = self.forward(*input, **kwargs)
 File "/r5/home/rruiz/software/anaconda3/envs/revisiting-models/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 124, in forward
   return F.embedding(
 File "/r5/home/rruiz/software/anaconda3/envs/revisiting-models/lib/python3.8/site-packages/torch/nn/functional.py", line 1852, in embedding
   return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self

Do you know why is this happening ?

Thanks a lot !!

Rbt

**Comment by rruizdeaustri** [comment]
Hi, 

The inputs in the tom input file are:

seed = 0

[data]
cat_policy = 'indices'
normalization = 'quantile'
path = 'data/4top'

[model]
d_embedding = 421
d_layers = [ 42, 503, 503, 503, 111 ]
dropout = 0.0

[training]
batch_size = 256
eval_batch_size = 256
lr = 0.0003214782880724119
n_epochs = 1000000000
optimizer = 'adamw'
patience = 16
weight_decay = 7.16873819458233e-05

Rbt

**Comment by Yura52** [comment]
The config looks valid, so I recommend checking the potential problem (that I described above) with categorical features before further debugging.

**Comment by rruizdeaustri** [comment]
Hi Yuri,

I'm investigating what is going on and found something weird in the encoding process.

Line C = {k: encoder.transform(v) for k, v in C.items}

I show you here two rows of the cat data:

['j' 'j' 'j' 'j' 'b' 'b' 'j' 'e' 'ep' 'null' 'null' 'null' 'null' 'null'
 'null' 'null' 'null' 'null' 'null']
['b' 'j' 'j' 'b' 'j' 'j' 'e' 'e' 'ep' 'null' 'null' 'null' 'null' 'null'
 'null' 'null' 'null' 'null' 'null']

-> after encoding:

[1 1 1 1 0 0 3 1 2 7 7 7 7 7 7 6 6 5 3]
[0 1 1 0 1 1 1 1 2 7 7 7 7 7 7 6 6 5 3]

I would expect that the "null" entrances to have the same integer (ie 7)
but it is not. 

Then the numbers do not follow a pattern.'j' can be 
1 or 3.


Am I missing something ?

Thanks

Rbt

**Comment by Yura52** [comment]
> two rows of the cat data

Do I understand correctly that
```
`['j' 'j' 'j' 'j' 'b' 'b' 'j' 'e' 'ep' 'null' 'null' 'null' 'null' 'null' 'null' 'null' 'null' 'null' 'null']`
```
are categorical features of one object, and 
```
['b' 'j' 'j' 'b' 'j' 'j' 'e' 'e' 'ep' 'null' 'null' 'null' 'null' 'null' 'null' 'null' 'null' 'null' 'null']
```
are categorical features of some other object?

If this is true, than the number of categorical features is:
```
n_cat_features ==
    == 19
    == len(['j' 'j' 'j' 'j' 'b' 'b' 'j' 'e' 'ep' 'null' 'null' 'null' 'null' 'null' 'null' 'null' 'null' 'null' 'null'])
    == len(['b' 'j' 'j' 'b' 'j' 'j' 'e' 'e' 'ep' 'null' 'null' 'null' 'null' 'null' 'null' 'null' 'null' 'null' 'null'])
```

and, for each of these 19 features the mapping `string -> index` can be (and often will be) different. In other words, the encoder thinks that each column contains different categories (for example, the first column contains country names, the second column contains city names etc.). If you want to change this and, moreover, if you want to use the same embeddings for different categorical columns, then you have to implement this, since, unfortunately, our implementation does not support this. It looks like you will need to add a new type of features for this purpose (in addition to "numerical" and "categorical").

**Comment by rruizdeaustri** [comment]
In the data I have, each line contains a series of particles with generated after collisions at the LHC collider. Each particle has 4 continues variables associated an a categorical one telling the type of particle. The issue is that the number of particles in a line is not fixed so zero-padding is added (ie the "null" cat.) 

Since the max. number of particles across the full dataset is 19 then I generate 19 categorical entrances, one for each particle in the event. Therefore, the structure I send you is for each raw of the data array I have:

first particle.type  second particle type ........... 

The particle type is coded as j (quarks), b (bottoms), e(electrons), etc ...

Could you pls tell me what would be the best way of econding this ?

**Comment by Yura52** [comment]
@rruizdeaustri sorry for the slow reply. Here is what I think about your problem.

In fact, treating the **same** types of particles with **different** indices as **different** particles (e.g. "quark when it is the second particle" and "quark when it is the third particle") can be a good approach, and this is exactly the approach you are trying to "fix". Since your data is inherently sequential, it can be beneficial for your task to assign different embeddings for the same particles when they are on different positions. Of course, I cannot guarantee that it will work well, but this is something I would try, especially given the fact that this approach allows reusing our code with minimal changes.

All other approaches require coding on your side, because our current implementation uses different embedding dictionaries for different categorical columns. The good news is that you can simply use `torch.nn.Embedding`. However, you have to encode all categories similarly regardless of their column indices. This is also something that we do not support in our code and you have to perform it manually. Importantly, this may not be enough and you may have to add positional embeddings to your categorical embeddings in the same manner as it is done in the original paper "Attention is all you need".

Also, you can (and probably should) take into account the fact that your objects are sequences. Namely:
- for transformer-based models, you can use attention masks to tell the attention mechanism that some tokens are missing. For example, if there are ten particles in your sequence, you may want the attention to ignore the "remaining" nine particles. Our implementation does not support masks. To support them, you have to pass sequence lengths everywhere. And you should use them to nullify the corresponding components of the `attention` variable **before** [this line](https://github.com/Yura52/tabular-dl-revisiting-models/blob/f65a93329a58c80ea486a212feeba6babf9fdd4f/bin/ft_transformer.py#L140).
- you can use recurrent neural networks

**Comment by Yura52** [comment]
Feel free to reopen the issue if help needed
